/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as HomeImport } from './routes/_home'
import { Route as DialogImport } from './routes/_dialog'
import { Route as HomeHomeTransactionsImport } from './routes/_home.home/transactions'
import { Route as HomeHomeContractsImport } from './routes/_home.home/contracts'
import { Route as HomeHomeConnectionsImport } from './routes/_home.home/connections'
import { Route as HomeHomeAccountImport } from './routes/_home.home/account'
import { Route as DialogDialogWalletUnlockIdImport } from './routes/_dialog.dialog/wallet-unlock.$id'
import { Route as DialogDialogTxReviewIdImport } from './routes/_dialog.dialog/tx-review.$id'
import { Route as DialogDialogMsgSignIdImport } from './routes/_dialog.dialog/msg-sign.$id'
import { Route as DialogDialogChainAddIdImport } from './routes/_dialog.dialog/chain-add.$id'

// Create/Update Routes

const OnboardingRoute = OnboardingImport.update({
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/_home',
  getParentRoute: () => rootRoute,
} as any)

const DialogRoute = DialogImport.update({
  id: '/_dialog',
  getParentRoute: () => rootRoute,
} as any)

const HomeHomeTransactionsRoute = HomeHomeTransactionsImport.update({
  path: '/home/transactions',
  getParentRoute: () => HomeRoute,
} as any)

const HomeHomeContractsRoute = HomeHomeContractsImport.update({
  path: '/home/contracts',
  getParentRoute: () => HomeRoute,
} as any)

const HomeHomeConnectionsRoute = HomeHomeConnectionsImport.update({
  path: '/home/connections',
  getParentRoute: () => HomeRoute,
} as any)

const HomeHomeAccountRoute = HomeHomeAccountImport.update({
  path: '/home/account',
  getParentRoute: () => HomeRoute,
} as any)

const DialogDialogWalletUnlockIdRoute = DialogDialogWalletUnlockIdImport.update(
  {
    path: '/dialog/wallet-unlock/$id',
    getParentRoute: () => DialogRoute,
  } as any,
)

const DialogDialogTxReviewIdRoute = DialogDialogTxReviewIdImport.update({
  path: '/dialog/tx-review/$id',
  getParentRoute: () => DialogRoute,
} as any)

const DialogDialogMsgSignIdRoute = DialogDialogMsgSignIdImport.update({
  path: '/dialog/msg-sign/$id',
  getParentRoute: () => DialogRoute,
} as any)

const DialogDialogChainAddIdRoute = DialogDialogChainAddIdImport.update({
  path: '/dialog/chain-add/$id',
  getParentRoute: () => DialogRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dialog': {
      id: '/_dialog'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DialogImport
      parentRoute: typeof rootRoute
    }
    '/_home': {
      id: '/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/_home/home/account': {
      id: '/_home/home/account'
      path: '/home/account'
      fullPath: '/home/account'
      preLoaderRoute: typeof HomeHomeAccountImport
      parentRoute: typeof HomeImport
    }
    '/_home/home/connections': {
      id: '/_home/home/connections'
      path: '/home/connections'
      fullPath: '/home/connections'
      preLoaderRoute: typeof HomeHomeConnectionsImport
      parentRoute: typeof HomeImport
    }
    '/_home/home/contracts': {
      id: '/_home/home/contracts'
      path: '/home/contracts'
      fullPath: '/home/contracts'
      preLoaderRoute: typeof HomeHomeContractsImport
      parentRoute: typeof HomeImport
    }
    '/_home/home/transactions': {
      id: '/_home/home/transactions'
      path: '/home/transactions'
      fullPath: '/home/transactions'
      preLoaderRoute: typeof HomeHomeTransactionsImport
      parentRoute: typeof HomeImport
    }
    '/_dialog/dialog/chain-add/$id': {
      id: '/_dialog/dialog/chain-add/$id'
      path: '/dialog/chain-add/$id'
      fullPath: '/dialog/chain-add/$id'
      preLoaderRoute: typeof DialogDialogChainAddIdImport
      parentRoute: typeof DialogImport
    }
    '/_dialog/dialog/msg-sign/$id': {
      id: '/_dialog/dialog/msg-sign/$id'
      path: '/dialog/msg-sign/$id'
      fullPath: '/dialog/msg-sign/$id'
      preLoaderRoute: typeof DialogDialogMsgSignIdImport
      parentRoute: typeof DialogImport
    }
    '/_dialog/dialog/tx-review/$id': {
      id: '/_dialog/dialog/tx-review/$id'
      path: '/dialog/tx-review/$id'
      fullPath: '/dialog/tx-review/$id'
      preLoaderRoute: typeof DialogDialogTxReviewIdImport
      parentRoute: typeof DialogImport
    }
    '/_dialog/dialog/wallet-unlock/$id': {
      id: '/_dialog/dialog/wallet-unlock/$id'
      path: '/dialog/wallet-unlock/$id'
      fullPath: '/dialog/wallet-unlock/$id'
      preLoaderRoute: typeof DialogDialogWalletUnlockIdImport
      parentRoute: typeof DialogImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DialogRoute: DialogRoute.addChildren({
    DialogDialogChainAddIdRoute,
    DialogDialogMsgSignIdRoute,
    DialogDialogTxReviewIdRoute,
    DialogDialogWalletUnlockIdRoute,
  }),
  HomeRoute: HomeRoute.addChildren({
    HomeHomeAccountRoute,
    HomeHomeConnectionsRoute,
    HomeHomeContractsRoute,
    HomeHomeTransactionsRoute,
  }),
  OnboardingRoute,
})

/* prettier-ignore-end */
